# Default values for legal-deploy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

data:
  requests_cpu: "0.25"
  requests_memory: "256M"
  limits_cpu: "1.5"
  limits_memory: "1G"
  serviceAccountName: ""
  imagePullPolicy: "IfNotPresent"
  image: ""

conf:
  configmap: "legal-config"
  app_name: "legal"
