server:
  servlet:
    contextPath: /api/legal/v1/
  port: 8080 

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://some.keycloak.com/auth/realms/OSDU/protocol/openid-connect/certs

REGION: us-central
AUTHORIZE_API: http://entitlements:8080/api/entitlements/v1
LEGAL_HOSTNAME: notused
CRON_JOB_IP: 10.0.0.1
LOG_PREFIX: legal

ibm:
  env:
    prefix: acceptance-test
  legal:
    publisher:
      devnull: true
    db:
      name: legal-tags
      credentials: file:/somepath
      user: change
      password: change
  tenant:
    db:
      name: tenant-info
      url: ${ibm.legal.db.url}
      user: ${ibm.legal.db.user}
      password: ${ibm.legal.db.password}
