variables:
  AWS_BUILD_SUBDIR: provider/legal-aws/build-aws
  AWS_TEST_SUBDIR: testing/legal-test-aws
  AWS_CHART_SUBDIR: devops/aws/chart
  AWS_SERVICE: legal
  AWS_SERVICE_GATEWAY: osdu-gateway
  AWS_ENVIRONMENT: dev
  AWS_DEPLOY_TARGET: TF
  AWS_EKS_DEPLOYMENT_NAME: os-legal

  MONGODB_AWS_SERVICE: legal
  MONGODB_AWS_BUILD_SUBDIR: provider/legal-aws/build-aws
  MONGODB_AWS_TEST_SUBDIR: testing/legal-test-aws
  MONGODB_AWS_EKS_DEPLOYMENT_NAME: os-legal

  GCP_BUILD_SUBDIR: provider/legal-gcp
  GCP_INT_TEST_SUBDIR: testing/legal-test-gcp
  GCP_APPLICATION_NAME: os-legal
  GCP_ENVIRONMENT: testing
  GCP_PROJECT: opendes-evt
  GCP_TENANT_NAME: opendes-evt

  IBM_BUILD_SUBDIR: provider/legal-ibm
  IBM_INT_TEST_SUBDIR: testing/legal-test-ibm

  AZURE_SERVICE: legal
  AZURE_BUILD_SUBDIR: provider/legal-azure
  AZURE_TEST_SUBDIR: testing/legal-test-azure

  IBM_HELM_CONFIG_PATH: devops/ibm/ibm-legal-config
  IBM_HELM_DEPLOY_PATH: devops/ibm/ibm-legal-deploy

  # Spotbugs is only intended for Groovy, Scala, or Koitlin development; not Maven+Java
  # The presence of provider/legal-ibm/src/test/resources/logback.groovy is tricking GitLab into including the job
  # We exclude it here to speed up pipeline execution, and avoid having the image fail on our Maven builds
  # Maven jobs should be using semgrep instead
  SAST_EXCLUDED_ANALYZERS: "spotbugs"

include:
  - project: "osdu/platform/ci-cd-pipelines"
    file: "standard-setup.yml"
    ref: m18-pipeline-update-mm

  - project: "osdu/platform/ci-cd-pipelines"
    file: "build/maven.yml"
    ref: m18-pipeline-update-mm

  - project: "osdu/platform/ci-cd-pipelines"
    file: "scanners/fossa-maven.yml"
    ref: m18-pipeline-update-mm

  - project: "osdu/platform/ci-cd-pipelines"
    file: "scanners/gitlab-ultimate.yml"
    ref: m18-pipeline-update-mm

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/aws-global.yml"
    ref: m18-pipeline-update-mm

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/aws-maven.yml"
    ref: m18-pipeline-update-mm

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/aws-mongodb-global.yml"
    ref: m18-pipeline-update-mm

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/aws-mongodb-maven.yml"
    ref: m18-pipeline-update-mm

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/ibm.yml"
    ref: m18-pipeline-update-mm

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/azure.yml"
    ref: m18-pipeline-update-mm

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/gc-global.yml"
    ref: m18-pipeline-update-mm

  - project: "osdu/platform/ci-cd-pipelines"
    file: "publishing/pages.yml"
    ref: m18-pipeline-update-mm

  - local: "devops/gc/pipeline/override-stages.yml"
