variables:
  AWS_BUILD_SUBDIR: provider/legal-aws
  AWS_APPLICATION_NAME: os-legal
  AWS_ENVIRONMENT: dev
  GCP_BUILD_SUBDIR: provider/legal-gcp
  GCP_INT_TEST_SUBDIR: testing/legal-test-gcp
  GCP_APPLICATION_NAME: osdu-legal
  GCP_ENVIRONMENT: dev
  GCP_PROJECT: opendes
  GCP_TENANT_NAME: opendes
  GCP_DEPLOY_ENV: p4d
  GCP_DOMAIN: cloud.slb-ds.com
  GCP_STORAGE_URL: https://osdu-legal-dot-opendes.appspot.com/api/legal/v2/
  AZURE_SERVICE: legal
  AZURE_BUILD_SUBDIR: provider/legal-azure
  AZURE_TEST_SUBDIR: testing/legal-test-azure


include:
  - project: "osdu/platform/ci-cd-pipelines"
    ref: "master"
    file: "standard-setup.yml"
  - project: "osdu/platform/ci-cd-pipelines"
    ref: "master"
    file: "build/maven.yml"
  - project: "osdu/platform/ci-cd-pipelines"
    ref: "master"
    file: "cloud-providers/azure.yml"
  - project: "osdu/platform/ci-cd-pipelines"
    file: "scanners/fossa.yml"
  - project: "osdu/platform/ci-cd-pipelines"
    file: "scanners/gitlab-ultimate.yml"


compile-and-unit-test:
  variables:
    GOOGLE_CLOUD_PROJECT: opendes
