apiVersion: v1
data:
    AUTHORIZE_API: ${AUTHORIZE_API}
    MONGO_DB_URL: ${MONGO_DB_URL}
    MONGO_DB_USER: ${MONGO_DB_USER}
    MONGO_DB_NAME: ${MONGO_DB_NAME}
    REGION: ${REGION}
kind: ConfigMap
metadata:
    labels:
        app: legal
    name: legal-config
    namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
    generateName: legal-anthos
    labels:
        app: legal
    name: legal
    namespace: default
spec:
    selector:
        matchLabels:
            app: legal
    replicas: 1
    template:
        metadata:
            labels:
                app: legal
        spec:
            containers:
                -   env:
                        -   name: AUTHORIZE_API
                            valueFrom:
                                configMapKeyRef:
                                    key: AUTHORIZE_API
                                    name: legal-config
                        -   name: MONGO_DB_URL
                            valueFrom:
                                configMapKeyRef:
                                    key: MONGO_DB_URL
                                    name: legal-config
                        -   name: MONGO_DB_USER
                            valueFrom:
                                configMapKeyRef:
                                    key: MONGO_DB_USER
                                    name: legal-config
                        -   name: MONGO_DB_PASSWORD
                            valueFrom:
                                secretKeyRef:
                                    name: legal-secret
                                    key: mongo.db.password
                        -   name: MONGO_DB_NAME
                            valueFrom:
                                configMapKeyRef:
                                    key: MONGO_DB_NAME
                                    name: legal-config
                        -   name: MB_RABBITMQ_URI
                            valueFrom:
                                secretKeyRef:
                                    name: legal-secret
                                    key: mb.rabbitmq.uri
                        -   name: REGION
                            valueFrom:
                                configMapKeyRef:
                                    key: REGION
                                    name: legal-config
                    image: us.gcr.io/osdu-anthos-02/os-legal/anthos-legal:latest
                    name: os-legal-1-sha256-1
---
apiVersion: v1
kind: Service
metadata:
    name: legal
    namespace: default
spec:
    ports:
        -   protocol: TCP
            port: 80
            targetPort: 8080
    selector:
        app: legal
    type: LoadBalancer
---
apiVersion: v1
data:
    mongo.db.password: ${MONGO_DB_PASSWORD}
    mb.rabbitmq.uri: ${MB_RABBITMQ_URI}
kind: Secret
metadata:
    name: legal-secret
    namespace: default
type: Opaque