# Default values for legal-deploy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  domain: ""
  onPremEnabled: false
  dataBootstrapEnabled: false
  limitsEnabled: true

data:
  # configmaps
  logLevel: "ERROR"
  springProfilesActive: "gcp"
  acceptHttp: "true"
  dataPartitionId: ""
  entitlementsHost: "http://entitlements"
  defaultLegalTag: "default-data-tag"
  legalHost: "http://legal"
  # deployments
  requestsCpu: "5m"
  requestsMemory: "325Mi"
  limitsCpu: "1"
  limitsMemory: "1G"
  bootstrapImage: ""
  legalStatusUpdateImage: ""
  bootstrapServiceAccountName: ""
  serviceAccountName: "legal"
  imagePullPolicy: "IfNotPresent"
  image: ""

conf:
  configmap: "legal-config"
  appName: "legal"
  minioSecretName: "legal-minio-secret"
  postgresSecretName: "legal-postgres-secret"
  rabbitmqSecretName: "rabbitmq-secret"
  bootstrapSecretName: "datafier-secret"
  replicas: 1

istio:
  proxyCPU: "5m"
  proxyCPULimit: "500m"
  proxyMemory: "50Mi"
  proxyMemoryLimit: "512Mi"
  bootstrapProxyCPU: "5m"
  bootstrapProxyCPULimit: "100m"
