# Copyright © Amazon Web Services
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

AWSTemplateFormatVersion: 2010-09-09
Description: >-
  CloudFormation template for creating the resources used for application SDK access for OSDU's legal service.
  It creates the IAM account, access keys, and optional key rotation.

Parameters:
  Environment:
    Description: An environment name that will be prefixed to resource names.
    Type: String
    AllowedValues:
      - dev
      - uat
      - prod
    ConstraintDescription: Can only be "dev/uat/prod"
    Default: dev

  Region:
    Description: The AWS region to deploy the resources to.
    Type: String
    Default: us-east-1

  LegalServiceIamUsername:
    Description: The username of the service user for the OS Legal service.
    AllowedPattern: "^[a-zA-Z]+[0-9a-zA-Z_-]*$"
    ConstraintDescription: Must start with a letter. Only numbers, letters, -, and _ accepted. Max. length 64 characters.
    Type: String
    Default: service-user-os-legal
    MinLength: '1'
    MaxLength: '64'

  LegalServiceIamKeyRotationSerial:
    Description: This integer value can only ever be incremented, and an increase in value results in a rotation of the user's access key.
    Type: Number
    Default: 1

Resources:
  LegalServiceIamUser:
    Type: AWS::IAM::User
    Properties:
      Policies:
        - PolicyName: !Sub ${Environment}-LegalServiceUserPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - 'dynamodb:*'
                  - 'logs:*'
                  - 'cloudwatch:*'
                  - 'lambda:*'
                  - 's3:*'
                  - 'sns:*'
                  - 'sqs:*'
                Effect: Allow
                Resource: '*'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
      UserName: !Sub ${Environment}-${LegalServiceIamUsername}

  LegalServiceIamUserAccessKey:
    Type: AWS::IAM::AccessKey
    DependsOn: LegalServiceIamUser
    Properties: 
      Serial: !Ref LegalServiceIamKeyRotationSerial # this value can only ever be incremented, and an increase in value results in a rotation of the user's access key
      Status: Active
      UserName: !Sub ${Environment}-${LegalServiceIamUsername}
      
  IAMCredentialsSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub ${Environment}-LegalServiceIamCredentials
      Description: The IAM service account credentials for the Legal service.
      SecretString:
        Fn::Sub:
          - '{"access_key":"${AccessKey}","secret_key":"${SecretKey}"}'
          - {AccessKey: !Ref LegalServiceIamUserAccessKey, SecretKey: !GetAtt LegalServiceIamUserAccessKey.SecretAccessKey}
      Tags:
        - Key: Environment
          Value: !Ref Environment

Outputs:
  LegalServiceIamUserAccessKeyId:
    Description: The access key ID for the service user for the OS Legal service.
    Value: !Ref LegalServiceIamUserAccessKey
    Export:
      Name: !Sub ${Environment}-LegalServiceIamUserAccessKeyId

  LegalServiceIamUserSecretAccessKey:
    Description: The secret access key for the service user for the OS Legal service.
    Value: !GetAtt LegalServiceIamUserAccessKey.SecretAccessKey
    Export:
      Name: !Sub ${Environment}-LegalServiceIamUserSecretAccessKey
      
  LegalServiceIamUserArn:
    Description: The name of the OSDU data Legal S3 bucket.
    Value: !GetAtt LegalServiceIamUser.Arn
    Export:
      Name: !Sub ${Environment}-LegalServiceIamUserArn