apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ .Values.conf.appName | quote }}
  name: {{ .Values.conf.configmap | quote }}
  namespace: {{ .Release.Namespace | quote }}
data:
  ACCEPT_HTTP: {{ .Values.data.acceptHttp | quote }}
  LOG_LEVEL: {{ .Values.data.logLevel | quote }}
