apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ printf "%s-legalstatus-update" .Values.conf.appName | quote }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  schedule: "@daily"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ printf "%s-legalstatus-update" .Values.conf.appName | quote }}
            image: {{ .Values.data.legalStatusUpdateImage | quote }}
            imagePullPolicy: {{ .Values.data.imagePullPolicy | quote }}
            envFrom:
            - configMapRef:
                name:  {{ printf "%s-status-update" .Values.conf.configmap | quote }}
            {{- if .Values.global.onPremEnabled }}
            - secretRef:
                name: {{ .Values.conf.bootstrapSecretName | quote }}
            {{- end }}
            securityContext:
              allowPrivilegeEscalation: false
              runAsNonRoot: true
          restartPolicy: OnFailure
          serviceAccountName: {{ .Values.data.cronJobServiceAccountName | quote }}
