apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ .Values.conf.appName | quote }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  hosts:
    - {{ .Values.global.domain | quote }}
  gateways:
    - service-gateway
  http:
    - match:
        - uri:
            prefix: "/api/legal/v1"
      route:
        - destination:
            port:
              number: 80
            host: {{ printf "%s.%s.svc.cluster.local" .Values.conf.appName .Release.Namespace | quote }}
