# Default values for legal-configmap.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

data:
  authorize_api: ""
  partition_api: ""
  log_level: ""
  enable_full_bucket_name: "true"
  project_id: ""
  google_audiences: ""
  accept_http: "true"
  spring_profiles_active: "gcp"

conf:
  ent_name: ""
  configmap: "legal-config"
  app_name: "legal"
