schemaVersion: 3
service:
  name: legal
  archetype: java-maven-azure
tests:
  acceptance:
    type: maven
    path: legal-acceptance-test
    mavenArguments: [test]
    timeoutMinutes: 15
    bindings:
      HOST: { source: gateway }
      DATA_PARTITION_ID: { source: partition }
      PRIVILEGED_USER_TOKEN: { source: token }
      EXPOSE_FEATUREFLAG_ENABLED: { source: static, value: "true" }
  integration:
    type: maven
    path: testing
    mavenArguments: [-pl, legal-test-azure, -am, "-Dtest=!TestDeleteLegalTagApiAcceptance#*SubscriptionMessage*,!TestValidateLegalTagsApiAcceptance#*GivenExistingInvalidLegalTagNames", -Dsurefire.failIfNoSpecifiedTests=false, test]
    timeoutMinutes: 20
    bindings:
      HOST_URL: { source: gateway, suffix: /api/legal/v1/ }
      MY_TENANT: { source: partition }
      INTEGRATION_TESTER_ACCESS_TOKEN: { source: token }
