#!/bin/bash

DATABASE_PREFIX=acceptance-test
BASE_URL=$(jq -r ".url" < ${IBM_CREDENTIALS_FILE})
USERNAME=$(jq -r ".username" < ${IBM_CREDENTIALS_FILE})
PASSWORD=$(jq -r ".password" < ${IBM_CREDENTIALS_FILE})

curl -XDELETE -u $USERNAME:$PASSWORD $BASE_URL/$DATABASE_PREFIX-countries
curl -XDELETE -u $USERNAME:$PASSWORD $BASE_URL/$DATABASE_PREFIX-legal-tags
curl -XDELETE -u $USERNAME:$PASSWORD $BASE_URL/$DATABASE_PREFIX-tenant-info
