apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: "{{ .Values.conf.app_name }}"
  name: "{{ .Values.conf.configmap }}"
  namespace: "{{ .Release.Namespace }}"
data:
  AUTHORIZE_API: "http://{{ .Values.conf.ent_name }}{{ .Values.data.authorize_api }}"
  LOG_LEVEL: "{{ .Values.data.log_level }}"
  ENABLE_FULL_BUCKET_NAME: "{{ .Values.data.enable_full_bucket_name }}"
  PROJECT_ID: "{{ .Values.data.project_id }}"
  AUDIENCES: "{{ .Values.data.audiences }}"
  REDIS_GROUP_HOST: "{{ .Values.data.redis_group_host }}"
  REDIS_STORAGE_HOST: "{{ .Values.data.redis_storage_host }}"
  ACCEPT_HTTP: "{{ .Values.data.accept_http }}"
