apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: "{{ .Values.conf.appName }}"
  name: "{{ .Values.conf.configmap }}"
  namespace: "{{ .Release.Namespace }}"
data:
  LOG_LEVEL: "{{ .Values.data.logLevel }}"
  SPRING_PROFILES_ACTIVE: "{{ .Values.data.springProfilesActive }}"
  {{- if not .Values.conf.onPremEnabled }}
  GOOGLE_AUDIENCES: "{{ .Values.data.googleAudiences }}"
  ACCEPT_HTTP: "{{ .Values.data.acceptHttp }}"
  {{- end }}
