apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: "{{ .Values.conf.app_name }}"
  name: "{{ .Values.conf.configmap }}"
  namespace: "{{ .Release.Namespace }}"
data:
  LOG_LEVEL: "{{ .Values.data.log_level }}"
  SPRING_PROFILES_ACTIVE: "{{ .Values.data.spring_profiles_active }}"
  {{- if not .Values.conf.on_prem_enabled }}
  GOOGLE_AUDIENCES: "{{ .Values.data.google_audiences }}"
  ACCEPT_HTTP: "{{ .Values.data.accept_http }}"
  {{- end }}
