variables:
  GC_SERVICE: legal
  GC_VENDOR: gc

gc-anthos-test:
  variables:
    GC_VENDOR: anthos

gc-containerize-bootstrap-gitlab:
  variables:
    GC_ENABLE_BOOTSTRAP: "true"

gc-containerize-bootstrap-gcr:
  variables:
    GC_ENABLE_BOOTSTRAP: "true"
